create database sales;
use sales;
create table orders(order_id int,customer_id int, order_date datetime default current_timestamp,
amount decimal(10,2) not null,primary key(order_id,customer_id));
insert into orders(order_id,customer_id,order_date,amount) values(1,01,'2024-11-10 06:04:10',150.00);
select * from orders;
select order_id from orders where amount=150.00;
insert into orders(order_id,customer_id,order_date,amount) values(2,02,'2024-04-25 10:30:00',200.50);
insert into orders(order_id,customer_id,order_date,amount) values(3,03,'2024-11-10 06:05:27',175.75);
insert into orders(order_id,customer_id,order_date,amount) values(4,04,'2024-11-10 06:05:27',220.00);
insert into orders(order_id,customer_id,order_date,amount) values(5,05,'2024-11-10 06:05:27',99.99);
select * from orders;
select order_id,customer_id from orders where order_id=1 and customer_id=01;
select order_id,customer_id from orders where order_id=1 or customer_id=01;
select order_id,customer_id from orders where order_id=1 and customer_id!=01;
select order_id , count(*) as id from orders group by order_id;
select count(order_id) as id from orders;
select amount , sum(amount) as adds from orders group by amount;
select amount , avg(amount) as avgs from orders group by amount;
select amount, min(amount) as mins from orders group by amount;
select customer_id,min(amount) as mins from orders group by customer_id;
select min(amount) from orders;
select sum(amount) from orders;
select date(order_date) as od, time(order_date) as ot from orders;
select min(amount) as mins,sum(amount) as sums from orders group by customer_id,order_id;
select min(amount) as mins,sum(amount) as sums from orders group by customer_id,order_id having customer_id>1 and order_id>1;
select min(amount) as mins,sum(amount) as sums from orders group by customer_id,order_id having customer_id>1 and order_id!=2;
select * from orders where order_id=1;
select amount from orders order by amount asc;
select amount from orders order by amount desc;
#the below query is used to retrieve only 2 rows in desc so first sorting in desc occurs then retrieving of only first two occurs;
select amount from orders order by amount desc limit 2;
select * from orders limit 4;
select distinct customer_id from orders;
select * from orders where order_date between '2024-01-01' and '2024-12-31';
select * from orders where customer_id in (1,2,3);
alter table orders add column order_name varchar(100) not null default 'clothes';
select * from orders;
update orders set order_name='cotton' where order_id=1;
select order_name from orders where order_id=1;
update orders set order_name='wool',amount=500.00 where order_id=2;
select order_name,amount from orders where order_id=2;
select * from orders where order_name like 'c%';
select * from orders where order_name like 'cotto%';
select * from orders where order_name like '%ton';
select * from orders where order_name like '%th';
select order_name from orders;
select * from orders where order_name like '%thes';
select order_id from orders where customer_id=1 union select order_id from orders where customer_id=2;
select order_id from orders where customer_id=1 union all select order_id from orders where customer_id=3;
select customer_id,case when amount>1000 then 'high' when amount between 120.00 and 150.00 then 'medium' else 'low' end as amount_category from orders;
select * from orders where order_name like '%tto%';
select * from orders where order_name like '%[cltn]%';
select * from orders where order_name like '%c%' or order_name like '%l%' or order_name like '%t%' or order_name like '%n%';
select * from orders;